version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    domainname: example.net
    image: puppet/puppetserver
    ports:
      - 8140
    volumes:
      - ./code:/etc/puppetlabs/code/
    environment:
      - PUPPETDB_SERVER_URLS=https://puppetdb.example.net:8081
#    links:
#      - puppetdb:puppetdb.example.net

  postgres:
    container_name: postgres
    image: puppet/puppetdb-postgres
    environment:
      - POSTGRES_PASSWORD=puppetdb
      - POSTGRES_USER=puppetdb
    expose:
      - 5432

  puppetdb:
    hostname: puppetdb
    domainname: example.net
    image: puppet/puppetdb
    ports:
      - 8080
      - 8081
    links:
      - postgres:postgres
      - puppet:puppet
